// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";

import { Provider } from "react-redux";
import { store } from "@/store/store";
import { ThemeProvider } from "styled-components";
import { useState, useEffect } from "react";
import GlobalStyle from "@/styles/GlobalStyle";
import Header from "@/components/Header";

// In layout.tsx (or a separate themes.ts file)
export const lightTheme = {
  bg: "#f8f9fa",
  text: "#212529",
  card: "#ffffff",
} as const;
export const darkTheme = {
  bg: "#121212",
  text: "#e0e0e0",
  card: "#1e1e1e",
} as const;

export type AppTheme = typeof lightTheme; // or typeof darkTheme (they match)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [theme, setTheme] = useState<"light" | "dark">("light"); // always start with 'light' on both server & client

  useEffect(() => {
    const saved = localStorage.getItem("theme") as "light" | "dark" | null;
    if (saved) setTheme(saved);
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    setTheme(newTheme);
    localStorage.setItem("theme", newTheme);
  };

  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
            <GlobalStyle />
            <Header theme={theme} toggleTheme={toggleTheme} />
            {children}
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
